# ============================================
# 场景配置：广泛新闻热点（默认）
# ============================================

metadata:
  name: "广泛新闻热点"
  description: "分析全领域的社会热点新闻和舆情"
  version: "1.0"
  author: "BettaFish Team"

# ===== 爬虫关键词提取配置 =====
crawler:
  topic_extraction:
    system_prompt: "你是一个专业的新闻分析师，擅长从热点新闻中提取关键词和撰写分析总结。"
    
    user_prompt_template: |
      请分析以下{news_count}条今日热点新闻，完成两个任务：
      
      新闻列表：
      {news_text}
      
      任务1：提取关键词（最多{max_keywords}个）
      - 提取能代表今日热点话题的关键词
      - 关键词应该适合用于社交媒体平台搜索
      - 优先选择热度高、讨论量大的话题
      - 避免过于宽泛或过于具体的词汇
      
      任务2：撰写新闻分析总结（150-300字）
      - 简要概括今日热点新闻的主要内容
      - 指出当前社会关注的重点话题方向
      - 分析这些热点反映的社会现象或趋势
      - 语言简洁明了，客观中性
      
      请严格按照以下JSON格式输出：
      ```json
      {{
        "keywords": ["关键词1", "关键词2", "关键词3"],
        "summary": "今日新闻分析总结内容..."
      }}
      ```
      
      请直接输出JSON格式的结果，不要包含其他文字说明。
    
    # 关键词过滤规则（可选）
    keyword_filters:
      include_patterns: []  # 必须包含的模式（正则表达式）
      exclude_patterns: []  # 必须排除的模式
      min_length: 2
      max_length: 20

# ===== QueryEngine配置 =====
query_engine:
  system_prompt: |
    你是一个专业的舆情分析师，擅长从新闻和网络内容中提取关键信息。
    你的任务是搜索和分析用户关心的话题，提供全面、客观的信息。
  
  analysis_focus:
    - "新闻事实和时间线"
    - "不同媒体的报道角度"
    - "公众讨论热点"
    - "相关背景信息"

# ===== MediaEngine配置 =====
media_engine:
  system_prompt: |
    你是一个多模态内容分析专家，擅长从视频、图片、文字等多种媒介中提取有价值的信息。
  
  analysis_focus:
    - "视觉内容关键信息"
    - "情感表达和氛围"
    - "传播方式和效果"

# ===== InsightEngine配置 =====
insight_engine:
  system_prompt: |
    你是一个数据分析专家，擅长从海量舆情数据中挖掘趋势和洞察。
  
  analysis_focus:
    - "情感分布和变化"
    - "讨论热度趋势"
    - "关键意见领袖观点"
    - "公众关注焦点"

# ===== ReportEngine配置 =====
report_engine:
  preferred_templates:
    - "社会公共热点事件分析报告模板.md"
    - "日常或定期舆情监测报告模板.md"
  
  report_style:
    tone: "客观中性"
    depth: "全面深入"
    focus: "事实与趋势"


